services:

  database:
    container_name: postgres
    image: postgres:13
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    volumes:
      - "./data/ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    networks:
      - backend

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    volumes:
      - "./data/pgadmin_data:/var/lib/pgadmin:rw"
    ports:
      - "8080:80"
    networks:
      - backend

networks:
  backend:
    name: pg-network

volumes:
  ny_taxi_postgres_data:
  pgadmin_data: